language: java
jdk:
  - openjdk 17.0.6 2023-01-17 LTS
  - OpenJDK Runtime Environment Corretto-17.0.6.10.1
  - OpenJDK 64-Bit Server VM Corretto-17.0.6.10.1

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - victorygainer@gmail.com