language: java

jdk:
  - openjdk version "17.0.6" 2023-01-17 LTS

global:
  - JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - victorygainer@gmail.com